# Generated by Django 5.0.6 on 2026-03-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_employee_id_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
